logging:
  level:
    org.springframework.security: warn

spring:
  application:
    name: Authorization Server

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  management:
    endpoints:
      web:
        exposure:
          include: health,metrics,info

---

spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization_service-db
    username: authorization_service
    password: authorization_service

server:
  port: 9090

logging:
  level:
    org.springframework.security: trace
---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://authorization_service-db:5432/authorization_service-db
    username: authorization_service
    password: authorization_service

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 80

logging:
  level:
    org.springframework.security: info

