logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: Authorization Server

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/authorization_service
    username: authorization_service
    password: authorization_service

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

